import { mergeAttributes, Node } from '@tiptap/core'

export interface HierarchyNodeOptions {
  /**
   * The HTML attributes for a hierarchy node.
   * @default {}
   * @example { class: 'hierarchy-container' }
   */
  HTMLAttributes: Record<string, any>

  /**
   * Enable auto-generation based on child document count
   * @default true
   */
  autoGenerate: boolean

  /**
   * Minimum child documents required for auto-generation
   * @default 2
   */
  minChildDocuments: number

  /**
   * Position for auto-generated hierarchy nodes
   * @default 'bottom'
   */
  autoPosition: 'top' | 'bottom'
}

export interface HierarchyNodeAttributes {
  /** 父文档ID */
  parentDocumentId: string | null

  /** 子文档ID列表 */
  childDocuments: string[]

  /** 是否自动生成 */
  autoGenerated: boolean

  /** 层级管理块类型 */
  hierarchyType: 'default' | 'compact' | 'tree'

  /** 显示模式 */
  displayMode: 'list' | 'grid' | 'cards'

  /** 是否可折叠 */
  collapsible: boolean

  /** 是否已折叠 */
  collapsed: boolean
}

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    hierarchyNode: {
      /**
       * Insert a hierarchy management node
       * @example editor.commands.insertHierarchyNode({ parentDocumentId: 'doc-123', childDocuments: ['child-1', 'child-2'] })
       */
      insertHierarchyNode: (options: {
        parentDocumentId: string
        childDocuments: string[]
        position?: 'top' | 'bottom' | 'cursor'
        autoGenerated?: boolean
        hierarchyType?: HierarchyNodeAttributes['hierarchyType']
        displayMode?: HierarchyNodeAttributes['displayMode']
      }) => ReturnType

      /**
       * Update hierarchy node with new child documents
       * @example editor.commands.updateHierarchyNode('block-id', ['child-1', 'child-2', 'child-3'])
       */
      updateHierarchyNode: (moniBlockId: string, childDocuments: string[]) => ReturnType

      /**
       * Add a child document to existing hierarchy node
       * @example editor.commands.addChildDocument('block-id', 'new-child-id')
       */
      addChildDocument: (moniBlockId: string, childDocumentId: string) => ReturnType

      /**
       * Remove a child document from hierarchy node
       * @example editor.commands.removeChildDocument('block-id', 'child-id')
       */
      removeChildDocument: (moniBlockId: string, childDocumentId: string) => ReturnType

      /**
       * Sync child documents for a parent document
       * @example editor.commands.syncChildDocuments('parent-doc-id')
       */
      syncChildDocuments: (parentDocumentId: string) => ReturnType

      /**
       * Toggle hierarchy node collapse state
       * @example editor.commands.toggleHierarchyCollapse('block-id')
       */
      toggleHierarchyCollapse: (moniBlockId: string) => ReturnType

      /**
       * Set hierarchy node display mode
       * @example editor.commands.setHierarchyDisplayMode('block-id', 'grid')
       */
      setHierarchyDisplayMode: (moniBlockId: string, mode: HierarchyNodeAttributes['displayMode']) => ReturnType
    }
  }
}

/**
 * HierarchyNode extension for parent-child document management
 *
 * This extension provides native support for hierarchical document structures,
 * allowing users to manage and navigate parent-child document relationships
 * directly within the TipTap editor.
 *
 * Features:
 * - Native hierarchy block insertion and management
 * - Auto-generation based on child document count
 * - Multiple display modes (list, grid, cards)
 * - Collapsible hierarchy sections
 * - Real-time child document synchronization
 * - Drag and drop support for reorganization
 *
 * @see https://docs.moni.ai/editor/hierarchy-node
 */
export const HierarchyNode = Node.create<HierarchyNodeOptions>({
  name: 'hierarchyNode',

  priority: 1000,

  addOptions() {
    return {
      HTMLAttributes: {},
      autoGenerate: true,
      minChildDocuments: 2,
      autoPosition: 'bottom',
    }
  },

  group: 'block',

  content: 'block*',

  addAttributes() {
    return {
      // 🔥 父文档关系属性
      parentDocumentId: {
        default: null,
        parseHTML: element => element.getAttribute('data-parent-document-id'),
        renderHTML: attributes => {
          if (attributes.parentDocumentId) {
            return { 'data-parent-document-id': attributes.parentDocumentId }
          }
          return {}
        },
      },

      // 🔥 子文档列表属性
      childDocuments: {
        default: [],
        parseHTML: element => {
          const childDocs = element.getAttribute('data-child-documents')
          return childDocs ? JSON.parse(childDocs) : []
        },
        renderHTML: attributes => {
          if (attributes.childDocuments && attributes.childDocuments.length > 0) {
            return { 'data-child-documents': JSON.stringify(attributes.childDocuments) }
          }
          return {}
        },
      },

      // 🔥 自动生成标识
      autoGenerated: {
        default: false,
        parseHTML: element => element.getAttribute('data-auto-generated') === 'true',
        renderHTML: attributes => {
          if (attributes.autoGenerated) {
            return { 'data-auto-generated': 'true' }
          }
          return {}
        },
      },

      // 🔥 层级类型属性
      hierarchyType: {
        default: 'default',
        parseHTML: element => element.getAttribute('data-hierarchy-type') || 'default',
        renderHTML: attributes => {
          if (attributes.hierarchyType && attributes.hierarchyType !== 'default') {
            return { 'data-hierarchy-type': attributes.hierarchyType }
          }
          return {}
        },
      },

      // 🔥 显示模式属性
      displayMode: {
        default: 'list',
        parseHTML: element => element.getAttribute('data-display-mode') || 'list',
        renderHTML: attributes => {
          if (attributes.displayMode && attributes.displayMode !== 'list') {
            return { 'data-display-mode': attributes.displayMode }
          }
          return {}
        },
      },

      // 🔥 可折叠属性
      collapsible: {
        default: true,
        parseHTML: element => element.getAttribute('data-collapsible') !== 'false',
        renderHTML: attributes => {
          if (attributes.collapsible === false) {
            return { 'data-collapsible': 'false' }
          }
          return {}
        },
      },

      // 🔥 折叠状态属性
      collapsed: {
        default: false,
        parseHTML: element => element.getAttribute('data-collapsed') === 'true',
        renderHTML: attributes => {
          if (attributes.collapsed) {
            return { 'data-collapsed': 'true' }
          }
          return {}
        },
      },

      // 继承所有 Moni 通用属性
      moniBlockId: {
        default: null,
        parseHTML: element => element.getAttribute('data-moni-block-id'),
        renderHTML: attributes => {
          if (attributes.moniBlockId) {
            return { 'data-moni-block-id': attributes.moniBlockId }
          }
          return {}
        },
      },
      moniBlockType: {
        default: null,
        parseHTML: element => element.getAttribute('data-moni-block-type'),
        renderHTML: attributes => {
          if (attributes.moniBlockType) {
            return { 'data-moni-block-type': attributes.moniBlockType }
          }
          return {}
        },
      },

      moniParentId: {
        default: null,
        parseHTML: element => element.getAttribute('data-moni-parent-id'),
        renderHTML: attributes => {
          if (attributes.moniParentId) {
            return { 'data-moni-parent-id': attributes.moniParentId }
          }
          return {}
        },
      },

      moniLevel: {
        default: 0,
        parseHTML: element => {
          const level = element.getAttribute('data-moni-level')
          return level ? parseInt(level, 10) : 0
        },
        renderHTML: attributes => {
          if (attributes.moniLevel !== undefined && attributes.moniLevel !== 0) {
            return { 'data-moni-level': attributes.moniLevel.toString() }
          }
          return {}
        },
      },
      // 🔥 拖拽/Stream 等运行时属性已移除
      // 现在通过 editor.storage.runtimeState 访问
      // 参见：packages/core/src/extensions/runtime-state.ts
    }
  },

  parseHTML() {
    return [{ tag: 'div[data-type="hierarchy-node"]' }, { tag: 'div.moni-hierarchy-node' }]
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'div',
      mergeAttributes(
        {
          'data-type': 'hierarchy-node',
          class: 'moni-hierarchy-node',
        },
        this.options.HTMLAttributes,
        HTMLAttributes,
      ),
      0,
    ]
  },

  addCommands() {
    return {
      insertHierarchyNode:
        options =>
        ({ commands, state }) => {
          const {
            parentDocumentId,
            childDocuments,
            position = 'cursor',
            autoGenerated = false,
            hierarchyType = 'default',
            displayMode = 'list',
          } = options

          // 生成唯一的 block ID
          const blockId = `hierarchy-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`

          const hierarchyNode = {
            type: this.name,
            attrs: {
              parentDocumentId,
              childDocuments,
              autoGenerated,
              hierarchyType,
              displayMode,
              moniBlockId: blockId,
            },
            content: [
              {
                type: 'paragraph',
                content: [
                  {
                    type: 'text',
                    text: `📁 子文档管理${autoGenerated ? ' (自动生成)' : ''} - ${childDocuments.length}个子文档`,
                  },
                ],
              },
            ],
          }

          // 根据位置插入
          switch (position) {
            case 'top':
              return commands.insertContentAt(0, hierarchyNode)
            case 'bottom':
              return commands.insertContentAt(state.doc.content.size, hierarchyNode)
            case 'cursor':
            default:
              return commands.insertContent(hierarchyNode)
          }
        },

      updateHierarchyNode:
        (moniBlockId, childDocuments) =>
        ({ tr, state }) => {
          let nodePos: number | null = null
          let node: any = null

          // 查找目标节点
          state.doc.descendants((descendant, pos) => {
            if (descendant.attrs?.moniBlockId === moniBlockId && descendant.type.name === this.name) {
              nodePos = pos
              node = descendant
              return false
            }
            return true
          })

          if (nodePos !== null && node) {
            // 更新属性
            const newAttrs = {
              ...node.attrs,
              childDocuments,
            }

            tr.setNodeMarkup(nodePos, undefined, newAttrs)
            return true
          }

          return false
        },

      addChildDocument:
        (moniBlockId, childDocumentId) =>
        ({ tr, state, dispatch }) => {
          let nodePos: number | null = null
          let node: any = null

          // 查找目标节点
          state.doc.descendants((descendant, pos) => {
            if (descendant.attrs?.moniBlockId === moniBlockId && descendant.type.name === this.name) {
              nodePos = pos
              node = descendant
              return false
            }
            return true
          })

          if (nodePos !== null && node) {
            const currentChildren = node.attrs.childDocuments || []

            // 避免重复添加
            if (!currentChildren.includes(childDocumentId)) {
              const newChildren = [...currentChildren, childDocumentId]
              const newAttrs = {
                ...node.attrs,
                childDocuments: newChildren,
              }

              tr.setNodeMarkup(nodePos, undefined, newAttrs)

              if (dispatch) {
                dispatch(tr)
              }

              return true
            }
          }

          return false
        },

      removeChildDocument:
        (moniBlockId, childDocumentId) =>
        ({ tr, state, dispatch }) => {
          let nodePos: number | null = null
          let node: any = null

          // 查找目标节点
          state.doc.descendants((descendant, pos) => {
            if (descendant.attrs?.moniBlockId === moniBlockId && descendant.type.name === this.name) {
              nodePos = pos
              node = descendant
              return false
            }
            return true
          })

          if (nodePos !== null && node) {
            const currentChildren = node.attrs.childDocuments || []
            const newChildren = currentChildren.filter((id: string) => id !== childDocumentId)

            const newAttrs = {
              ...node.attrs,
              childDocuments: newChildren,
            }

            tr.setNodeMarkup(nodePos, undefined, newAttrs)

            if (dispatch) {
              dispatch(tr)
            }

            return true
          }

          return false
        },

      syncChildDocuments:
        parentDocumentId =>
        ({ state }) => {
          // 查找所有相关的层级管理块
          let foundNodes = 0

          state.doc.descendants(node => {
            if (node.type.name === this.name && node.attrs?.parentDocumentId === parentDocumentId) {
              foundNodes += 1
              // 标记需要同步 - 上层可以通过 updateHierarchyNode 来更新具体的子文档列表
            }
            return true
          })

          return foundNodes > 0
        },

      toggleHierarchyCollapse:
        moniBlockId =>
        ({ tr, state }) => {
          let nodePos: number | null = null
          let node: any = null

          // 查找目标节点
          state.doc.descendants((descendant, pos) => {
            if (descendant.attrs?.moniBlockId === moniBlockId && descendant.type.name === this.name) {
              nodePos = pos
              node = descendant
              return false
            }
            return true
          })

          if (nodePos !== null && node) {
            const newAttrs = {
              ...node.attrs,
              collapsed: !node.attrs.collapsed,
            }

            tr.setNodeMarkup(nodePos, undefined, newAttrs)
            return true
          }

          return false
        },

      setHierarchyDisplayMode:
        (moniBlockId, mode) =>
        ({ tr, state }) => {
          let nodePos: number | null = null
          let node: any = null

          // 查找目标节点
          state.doc.descendants((descendant, pos) => {
            if (descendant.attrs?.moniBlockId === moniBlockId && descendant.type.name === this.name) {
              nodePos = pos
              node = descendant
              return false
            }
            return true
          })

          if (nodePos !== null && node) {
            const newAttrs = {
              ...node.attrs,
              displayMode: mode,
            }

            tr.setNodeMarkup(nodePos, undefined, newAttrs)
            return true
          }

          return false
        },
    }
  },

  addKeyboardShortcuts() {
    return {
      // Ctrl+Shift+H: 插入层级管理块
      'Mod-Shift-h': () => {
        // 直接插入一个基本的层级管理块
        // 上层可以通过配置 parentDocumentId 和 childDocuments 来定制
        return this.editor.commands.insertHierarchyNode({
          parentDocumentId: '',
          childDocuments: [],
          position: 'cursor',
          autoGenerated: false,
          hierarchyType: 'default',
          displayMode: 'list',
        })
      },
    }
  },

  // 添加节点视图支持（可选）
  // addNodeView() {
  //   // 返回 null 表示使用默认渲染
  //   // 如果需要自定义渲染，可以在这里返回自定义的 NodeView
  //   return null
  // },

  // 添加插件支持
  addProseMirrorPlugins() {
    return [
      // 可以在这里添加特定于 HierarchyNode 的插件
      // 例如：自动同步、拖拽处理等
    ]
  },
})
